---
# Many thanks to marvinpinto for both the action and the example docs on how to
# use it.
# https://github.com/marvinpinto/action-automatic-releases

# Create automatic pre-release releases when `main` changes.
name: Pre-releases
on:
  push:
    branches:
      - main
jobs:
  pre-release:
    name: Pre Release
    runs-on: ubuntu-latest
    steps:
      # TODO: Add build and/or test
      - uses: "marvinpinto/action-automatic-releases@1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: latest
          prerelease: true
          title: Development Build
          # No files should be uploaded; simply pull from source control.

# Real releases from tagged versions
name: Tagged-releases
on:
  push:
    tags:
      # Any tags with the format "vx.y.z", or actually any "vblah".
      # TODO: Restrict this more sensibly.
      - "v*"
jobs:
  tagged-release:
    name: Tagged Release
    runs-on: ubuntu-latest
    steps:
      # TODO: Add build and/or test
      - uses: "marvinpinto/action-automatic-releases@1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            php-seq.php
