name: PHP Linting
on: pull_request
jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v1
        - name: php lint
          uses: michaelw90/PHP-Lint@master
